[app]
name = "Pacman"
category = "Badge"

[entry]
class = "Pacman"

[metadata]
author = "pikesley"
license = "MIT"
url = "https://www.github.com/"
description = "Pacman and some ghosts chasing around your Tildagon"
version = "0.0.2"
